transport= ["Bike", "Car", "Train"]
transport.append("Cycle")
print(transport)
another_transport=["Flight"]
transport.extend(another_transport)
print(transport)
transport.remove("Cycle")
print(transport)
removed_item=transport.pop(2)
print("Removed Item:",removed_item)
print(transport)
count=transport.count("Bike")
print("count of bike",count)
transport.reverse()
print("Reveresd List",transport)
new_transport=transport.copy()
print("Copied List",new_transport)
transport.clear()
print(transport)