set1={"Apple","mango","cherry"}
set1.add("plam")
print(set1)
new_items={"banana"}
set1.update(new_items)
print(set1)
set1.remove("plam")
print(set1)
set1.discard("banana")
print(set1)
item=set1.pop()
print("Removed:",item)
print(set1)
set2={"Apple","Blueberry"}
print("Union:",set1.union(set2))
print("Intersection:",set1.intersection(set2))
set1.clear()
print("Cleared",set1)